### PR TITLE
ImgSPEC Merge

### PR DESCRIPTION
**Pull request by winstonolson**
This merge introduces the `.imgspec` folder to the repository containing scripts and config files necessary to run SpectralUnmixing on the [ImgSPEC](https://www.imgspec.org) platform.  ImgSPEC is a 2-year AIST project with the goal of deploying a web-based and cloud-based software data system for developing spectroscopy algorithms using an online development environment and executing batch jobs at scale.

The  new `.imgspec` folder contains the following:
* `.imgspec/algorithm_config.yaml`: A config file describing what SpectralUnmixing needs to run on ImgSPEC.
*  `.imgspec/install.sh`: An build script for installing SpectralUnmixing dependencies into a Docker image
* `.imgspec/imgspec_run.sh`: A top level run script that converts the SpectralUnmixing inputs into a format that can be used with `unmix.jl`
* `.imgspec/*.py`: Miscellaneous helper scripts used by `.imgspec_run.sh`

### CODE REVIEW

**Comment by winstonolson** [comment]
@pgbrodrick, if this looks good, go ahead and merge (or let me know and I can do it).  Also, I'd like to create a 0.1.0 release once its done.  Thanks!

**Comment by pgbrodrick** [comment]
Hey @winstonolson  - the code here looks fine, but I'm wondering if it doesn't make more sense to place in an imgspec repository?

Some of this can fall under setup/install, but some (e.g. getting granule names) is tangential to this package.  In particular, this makes me concerned about maintenance.

Open to thoughts and feedback from all!

**Comment by winstonolson** [comment]
@pgbrodrick - Are you suggesting to move the whole `.imgspec` folder to a separate repo or just the utility scripts (in this case just `get_paths_from_granules.py`)? I suppose we could create imgspec wrapper repositories to contain the imgspec code.  That hasn't been the model so far, but it seems doable.

For the time being, however, we normally need to include the `algorithm_config.yaml` and `imgspec_run.sh` files for imgspec compatibility.  The `install.sh` script is new and allows for easier Docker creation.  In this case, it is needed for the Julia installs.  

The `get_paths_from_granules.py` file is a helper utility that could probably be added to a common imgspec repo since it can be reused.  That's a good suggestion and I can look into doing that for a future release.

**Comment by pgbrodrick** [comment]
Given some followup conversations, we're going to move to fold this in as it does no harm.  However, we'll look to migrate the contents of .imgspec back out in the long term, as they're more sustainable if hosted in an imgspec respository.

**Pull request merged**
